### ISSUE TITLE
Decode error on “train1.py”

### ISSUE THREAD

**Issue by HudsonHuang** [andabi/deep-voice-conversion#10]
Traceback (most recent call last):
  File "train1.py", line 88, in <module>
    train(logdir=logdir)
  File "train1.py", line 58, in train
    mfcc, ppg = get_batch(model.mode, model.batch_size)
  File "/home/lab-huang.zhongyi/workspace/deep-voice-conversion-master/data_load.py", line 259, in get_batch
    mfcc, ppg = map(_get_zero_padded, zip(*map(lambda w: get_mfccs_and_phones(w, hp_default.sr), target_wavs)))
  File "/home/lab-huang.zhongyi/workspace/deep-voice-conversion-master/data_load.py", line 259, in <lambda>
    mfcc, ppg = map(_get_zero_padded, zip(*map(lambda w: get_mfccs_and_phones(w, hp_default.sr), target_wavs)))
  File "/home/lab-huang.zhongyi/workspace/deep-voice-conversion-master/data_load.py", line 39, in get_mfccs_and_phones
    for line in open(phn_file, 'r').read().splitlines():
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 1024: invalid start byte

**Comment by pmsinner** [comment]
In my case the error was in extensions of sound files in TIMIT -- it was '.WAV' instead of '.wav'. It can be helpful to change `''WAV"` to `"wav"` in line 35 of data_load.py

**Comment by HudsonHuang** [comment]
Thank you @pmsinner , It works!
