### ISSUE TITLE
Train1.py  : AttributeError: 'numpy.ufunc' object has no attribute '__module__'

### ISSUE THREAD

**Issue by sallyjoy** [andabi/deep-voice-conversion#102]
Help! How to solve this?
-----------------------------

Traceback (most recent call last):
  File "train1.py", line 10, in <module>
    from tensorpack.callbacks.saver import ModelSaver
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/__init__.py", line 17, in <module>
    from tensorpack.models import *
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/__init__.py", line 48, in <module>
    _global_import(module_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/__init__.py", line 29, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/regularize.py", line 25, in <module>
    l2_regularizer = tf.contrib.layers.l2_regularizer
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import factorization
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 88, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/__init__.py", line 4, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/usr/local/lib/python2.7/dist-packages/dask/array/__init__.py", line 9, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/usr/local/lib/python2.7/dist-packages/dask/array/routines.py", line 256, in <module>
    @wraps(np.matmul)
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'

**Comment by oguzzkck** [comment]
How to solve this?
