### ISSUE TITLE
Help needed in restoring

### ISSUE THREAD

**Issue by YashBangera7** [andabi/deep-voice-conversion#105]
Process _Worker-4:
Traceback (most recent call last):
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\dataflow\parallel.py", line 169, in run
    for dp in self.ds:
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\dataflow\common.py", line 115, in __iter__
    for data in self.ds:
  File "D:\Deep Voice\deep-voice-conversion-master\data_load.py", line 40, in get_data
    yield get_mfccs_and_spectrogram(wav_file)
  File "D:\Deep Voice\deep-voice-conversion-master\data_load.py", line 134, in get_mfccs_and_spectrogram
    return _get_mfcc_and_spec(wav, hp.default.preemphasis, hp.default.n_fft, hp.default.win_length, hp.default.hop_length)
  File "D:\Deep Voice\deep-voice-conversion-master\data_load.py", line 150, in _get_mfcc_and_spec
    hp.default.sr, hp.default.n_fft, hp.default.n_mels)  # (n_mels, 1+n_fft//2)
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\filters.py", line 247, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,569) (0,)

**Comment by YashBangera7** [comment]
If anybody know how to resolve this please help me.
