### ISSUE TITLE
NotImplementedError in train2,py

### ISSUE THREAD

**Issue by YashBangera7** [andabi/deep-voice-conversion#106]
(dlwin36) D:\Deep Voice\deep-voice-conversion-master>python train2.py -ckpt model-936500
case: None, logdir1: cases/None/train1, logdir2: cases/None/train2
[0417 02:48:31 @logger.py:125] WRN Log directory cases/None/train2 exists! Use 'd' to delete it.
[0417 02:48:31 @logger.py:128] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.
Select Action: k (keep) / d (delete) / q (quit):k
[0417 02:48:38 @logger.py:83] Existing log file 'cases/None/train2\log.log' backuped to 'cases/None/train2\log.log.0417-024838'
[0417 02:48:38 @logger.py:90] Argv: train2.py -ckpt model-936500
[0417 02:48:38 @parallel.py:183] WRN MultiProcessPrefetchData does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0417 02:48:38 @parallel.py:193] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0417 02:49:11 @sesscreate.py:38] WRN User-provided custom session config may not work due to TF bugs. See https://github.com/tensorpack/tensorpack/issues/497 for workarounds.
Traceback (most recent call last):
  File "train2.py", line 93, in <module>
    train(args, logdir1=logdir_train1, logdir2=logdir_train2)
  File "train2.py", line 62, in train
    launch_train_with_config(train_conf, trainer=trainer)
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\train\interface.py", line 90, in launch_train_with_config
    model.get_input_signature(), input,
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\utils\argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\graph_builder\model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\graph_builder\model_desc.py", line 116, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by YashBangera7** [comment]
Please help me resolve the issue. I beg of you. :)

**Comment by ozler** [comment]
hi YashBangera7 how did you run train 1 did it like the python train1.py '22'

**Comment by YashBangera7** [comment]
@ozler i ran it like this : python train1.py -case "TIMIT_RUN2_carl" -gpu 0
The -case "TIMIT_RUN2_carl" can be any argument . (The case name for your training, will be used later)
Were u able to get rid of the error u have put in issue?
NotImplementedError() ? 
I dont understand it

**Comment by halluca** [comment]
@YashBangera7      I encounter this problem,do you have any idea where go wrong?
env) ☁ deep-voice-conversion-master  python train1.py timit
/home/fangguiping/env_project/deep-voice-conversion-master/deep-voice-conversion-master/hparam.py:11: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for doc in docs:
case: timit, logdir: ./data/logdir/timit/train1
[0423 11:22:32 @logger.py:90] Argv: train1.py timit
[0423 11:22:32 @parallel.py:193] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0423 11:22:32 @training.py:50] [DataParallel] Training a model of 2 towers.
[0423 11:22:32 @interface.py:43] Automatically applying StagingInput on the DataFlow.
Traceback (most recent call last):
  File "train1.py", line 78, in <module>
    train(args, logdir=logdir_train1)
  File "train1.py", line 60, in train
    launch_train_with_config(train_conf, trainer=trainer)
  File "/home/fangguiping/env_project/env/local/lib/python2.7/site-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    model.get_input_signature(), input,
  File "/home/fangguiping/env_project/env/local/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/home/fangguiping/env_project/env/local/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "/home/fangguiping/env_project/env/local/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 116, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by sebasdeldi** [comment]
stuck at the same point :(

**Comment by LucasMoskun** [comment]
I am also trying to understand this error. (In train1.py)

**Comment by LucasMoskun** [comment]
It looks like the function that is being called in the tensorboard model_desc folder has been depreciated, the body of the function has been totally removed and just throws the error: [Link to model_desc.py history](https://github.com/tensorpack/tensorpack/commit/4057c53152d564fdfa958fb146e0b5b3cb266af8#diff-323fb9e317f17564119e6e87c3a62229)

**Comment by LucasMoskun** [comment]
For a hack fix, this version of release of tensorpack seems to be compiling: (0.9.0.1) https://github.com/tensorpack/tensorpack/archive/0.9.0.1.zip
