### ISSUE TITLE
python-prctl

### ISSUE THREAD

**Issue by ozler** [andabi/deep-voice-conversion#107]
Hi python-prctl problem 
root@stable:/home/stable/Masaüstü/deep-voice-conversion-master# python train1.py 'test'
/usr/local/lib/python2.7/dist-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/stable/Masaüstü/deep-voice-conversion-master/hparam.py:11: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for doc in docs:
case: test, logdir: test
[0420 17:51:00 @logger.py:90] Argv: train1.py test
[0420 17:51:00 @parallel.py:193] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Process _Worker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/dataflow/parallel.py", line 165, in run
    enable_death_signal(_warn=self.idx == 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/concurrency.py", line 193, in enable_death_signal
    "prctl.set_pdeathsig does not exist! Note that you need to install 'python-prctl' instead of 'prctl'."
AssertionError: prctl.set_pdeathsig does not exist! Note that you need to install 'python-prctl' instead of 'prctl'.
Process _Worker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/dataflow/parallel.py", line 165, in run
    enable_death_signal(_warn=self.idx == 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/concurrency.py", line 193, in enable_death_signal
    "prctl.set_pdeathsig does not exist! Note that you need to install 'python-prctl' instead of 'prctl'."
AssertionError: prctl.set_pdeathsig does not exist! Note that you need to install 'python-prctl' instead of 'prctl'.
[0420 17:51:00 @training.py:50] [DataParallel] Training a model of 2 towers.
[0420 17:51:00 @training.py:52] ERR [DataParallel] TensorFlow was not built with CUDA support!
[0420 17:51:00 @interface.py:43] Automatically applying StagingInput on the DataFlow.
Process _Worker-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/dataflow/parallel.py", line 165, in run
    enable_death_signal(_warn=self.idx == 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/concurrency.py", line 193, in enable_death_signal
    "prctl.set_pdeathsig does not exist! Note that you need to install 'python-prctl' instead of 'prctl'."
AssertionError: prctl.set_pdeathsig does not exist! Note that you need to install 'python-prctl' instead of 'prctl'.
Process _Worker-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/dataflow/parallel.py", line 165, in run
    enable_death_signal(_warn=self.idx == 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/concurrency.py", line 193, in enable_death_signal
    "prctl.set_pdeathsig does not exist! Note that you need to install 'python-prctl' instead of 'prctl'."
AssertionError: prctl.set_pdeathsig does not exist! Note that you need to install 'python-prctl' instead of 'prctl'.
Traceback (most recent call last):
  File "train1.py", line 78, in <module>
    train(args, logdir=logdir_train1)
  File "train1.py", line 60, in train
    launch_train_with_config(train_conf, trainer=trainer)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    model.get_input_signature(), input,
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/graph_builder/model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/graph_builder/model_desc.py", line 116, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by halluca** [comment]
have you solved the problem? I'm stuck here @ozler

**Comment by ozler** [comment]
@halluca 
unfortunately could not solve

**Comment by sebasdeldi** [comment]
Facing the exact same issue!

**Comment by 497354078** [comment]
I have solved it by using "pip uninstall prctl"

**Comment by kyuer** [comment]
sudo apt-get install build-essential libcap-dev
pip install python-prctl
pip uninstall prctl
