### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by ArtemisZGL** [andabi/deep-voice-conversion#111]
when i run to 20 or 30 epoches, this error appear, but before that, there is no other error occur, what is the problem? thx.

[0508 00:52:10 @base.py:272] Start Epoch 34 ...

  0%|          |0/100[00:00<?,?it/s]Process _Worker-4:
Traceback (most recent call last):
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/tensorpack/dataflow/parallel.py", line 163, in ru

n
    for dp in self.ds:
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 116, in __it

er__
    for data in self.ds:
  File "/home/gongke/zgl/deep-voice-conversion-master/data_load.py", line 35, in get_data
    yield get_mfccs_and_phones(wav_file=wav_file)
  File "/home/gongke/zgl/deep-voice-conversion-master/data_load.py", line 72, in get_mfccs_and_phones
    wav = read_wav(wav_file, sr=hp.default.sr)
  File "/home/gongke/zgl/deep-voice-conversion-master/audio.py", line 13, in read_wav
    wav, _ = librosa.load(path, mono=mono, sr=sr, duration=duration)
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/audioread/__init__.py", line 85, in audio_open
    if _ca_available():
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/audioread/__init__.py", line 59, in _ca_available

    lib = ctypes.util.find_library('AudioToolbox')
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/ctypes/util.py", line 274, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/ctypes/util.py", line 103, in _findLib_gcc
    stdout=subprocess.PIPE)
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Process _Worker-1:
Traceback (most recent call last):
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/tensorpack/dataflow/parallel.py", line 163, in ru

n
    for dp in self.ds:
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 116, in __it

er__
    for data in self.ds:
  File "/home/gongke/zgl/deep-voice-conversion-master/data_load.py", line 35, in get_data
    yield get_mfccs_and_phones(wav_file=wav_file)
  File "/home/gongke/zgl/deep-voice-conversion-master/data_load.py", line 72, in get_mfccs_and_phones
    wav = read_wav(wav_file, sr=hp.default.sr)
  File "/home/gongke/zgl/deep-voice-conversion-master/audio.py", line 13, in read_wav
    wav, _ = librosa.load(path, mono=mono, sr=sr, duration=duration)
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
NoBackendError
Process _Worker-2:
Traceback (most recent call last):
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/tensorpack/dataflow/parallel.py", line 163, in ru

n
    for dp in self.ds:
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 116, in __it

er__
    for data in self.ds:
  File "/home/gongke/zgl/deep-voice-conversion-master/data_load.py", line 35, in get_data
    yield get_mfccs_and_phones(wav_file=wav_file)
  File "/home/gongke/zgl/deep-voice-conversion-master/data_load.py", line 72, in get_mfccs_and_phones
    wav = read_wav(wav_file, sr=hp.default.sr)
  File "/home/gongke/zgl/deep-voice-conversion-master/audio.py", line 13, in read_wav
    wav, _ = librosa.load(path, mono=mono, sr=sr, duration=duration)
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/audioread/__init__.py", line 85, in audio_open
    if _ca_available():
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/audioread/__init__.py", line 59, in _ca_available

    lib = ctypes.util.find_library('AudioToolbox')
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/ctypes/util.py", line 274, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/ctypes/util.py", line 103, in _findLib_gcc
    stdout=subprocess.PIPE)
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Process _Worker-3:
Traceback (most recent call last):
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/tensorpack/dataflow/parallel.py", line 163, in ru

n
    for dp in self.ds:
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 116, in __it

er__
    for data in self.ds:
  File "/home/gongke/zgl/deep-voice-conversion-master/data_load.py", line 35, in get_data
    yield get_mfccs_and_phones(wav_file=wav_file)
  File "/home/gongke/zgl/deep-voice-conversion-master/data_load.py", line 72, in get_mfccs_and_phones
    wav = read_wav(wav_file, sr=hp.default.sr)
  File "/home/gongke/zgl/deep-voice-conversion-master/audio.py", line 13, in read_wav
    wav, _ = librosa.load(path, mono=mono, sr=sr, duration=duration)
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/data2/wyx/anaconda3/envs/zgl_env3/lib/python2.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
NoBackendError

**Comment by ArtemisZGL** [comment]
it's because i install ffmpeg by conda, after i install it by another way, this problem is fixed
