### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/data'

### ISSUE THREAD

**Issue by syedKhutub** [andabi/deep-voice-conversion#112]
(venv) vyshnavi@vyshnavi-Inspiron-3558:~/Desktop/deep-voice-conversion-master$ python train1.py firsttrain
/home/vyshnavi/Desktop/deep-voice-conversion-master/hparam.py:11: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for doc in docs:
Traceback (most recent call last):
  File "train1.py", line 78, in <module>
    train(args, logdir=logdir_train1)
  File "train1.py", line 32, in train
    logger.set_logger_dir(logdir)
  File "/home/vyshnavi/venv/local/lib/python2.7/site-packages/tensorpack/utils/logger.py", line 149, in set_logger_dir
    mkdir_p(dirname)
  File "/home/vyshnavi/venv/local/lib/python2.7/site-packages/tensorpack/utils/fs.py", line 29, in mkdir_p
    raise e
OSError: [Errno 13] Permission denied: '/data'
i am not able to understand what the issue is over here

**Comment by LeoniusChen** [comment]
> (venv) vyshnavi@vyshnavi-Inspiron-3558:~/Desktop/deep-voice-conversion-master$ python train1.py firsttrain
> /home/vyshnavi/Desktop/deep-voice-conversion-master/hparam.py:11: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> for doc in docs:
> Traceback (most recent call last):
> File "train1.py", line 78, in 
> train(args, logdir=logdir_train1)
> File "train1.py", line 32, in train
> logger.set_logger_dir(logdir)
> File "/home/vyshnavi/venv/local/lib/python2.7/site-packages/tensorpack/utils/logger.py", line 149, in set_logger_dir
> mkdir_p(dirname)
> File "/home/vyshnavi/venv/local/lib/python2.7/site-packages/tensorpack/utils/fs.py", line 29, in mkdir_p
> raise e
> OSError: [Errno 13] Permission denied: '/data'
> **I am not able to understand what the issue is over here**
In default.yaml, you are not setting the right path.You should change the path containing your data.
