### ISSUE TITLE
Does anyone succesfully used one gpu with docker?

### ISSUE THREAD

**Issue by alemelis** [andabi/deep-voice-conversion#119]
Using the `Dockerfile` in `scripts` folder I managed to start `train1.py`

```
[1010 11:14:00 @base.py:158] Setup callbacks graph ...
[1010 11:14:00 @summary.py:34] Maintain moving average summary of 0 tensors.
[1010 11:14:02 @base.py:174] Creating the session ...
2019-10-10 11:14:02.528831: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-10 11:14:02.660072: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-10 11:14:02.661434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:01:00.0
totalMemory: 11.91GiB freeMemory: 11.29GiB
2019-10-10 11:14:02.661929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2019-10-10 11:14:03.584727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-10 11:14:03.584761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2019-10-10 11:14:03.584779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2019-10-10 11:14:03.585635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 12072 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0, compute capability: 6.1)
[1010 11:14:04 @base.py:182] Initializing the session ...
[1010 11:14:04 @base.py:189] Graph Finalized.
2019-10-10 11:14:06.635234: W tensorflow/core/kernels/queue_base.cc:285] _0_QueueInput/input_queue: Skipping cancelled dequeue attempt with queue not closed
[1010 11:14:06 @concurrency.py:36] Starting EnqueueThread QueueInput/input_queue ...
[1010 11:14:06 @graph.py:70] Running Op sync_variables_from_main_tower ...
[1010 11:14:07 @base.py:209] Start Epoch 1 ...
 12%|########2                                                            |12/100[00:32<01:59, 0.73it/s]
```

However, you can see how it's extremely slow. Even though my GPU is recognised and the memory allocated, this is the actual usage from `nvidia-smi`

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.14       Driver Version: 430.14       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:01:00.0  On |                  N/A |
| 26%   49C    P2    55W / 250W |   1884MiB / 12194MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

ideas?

**Comment by JcShang** [comment]
Hi, I used the same dockerfile. But when I run train1.py I got this error:
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train1.py", line 17, in <module>
    from data_load import Net1DataFlow
  File "/tmp/deep-voice-conversion-master/data_load.py", line 7, in <module>
    import librosa
  File "/usr/local/lib/python2.7/dist-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/__init__.py", line 108, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python2.7/dist-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/librosa/util/utils.py", line 103, in <module>
    def valid_audio(y, mono=True):
  File "/usr/local/lib/python2.7/dist-packages/librosa/cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
  File "/usr/local/lib/python2.7/dist-packages/joblib/memory.py", line 918, in cachedir
    DeprecationWarning, stacklevel=2)
TypeError: expected string or buffer

Have you met the same error?

**Comment by dudenas** [comment]
same problem. By inspecting the GPU usage, it's weird to see it going from 4 to 40 without getting to any stable constant
