### ISSUE TITLE
Problems I encountered when running train1

### ISSUE THREAD

**Issue by neil3212080** [andabi/deep-voice-conversion#123]
Traceback (most recent call last):
  File "train1.py", line 79, in <module>
    train(args, logdir=logdir_train1)
  File "train1.py", line 60, in train
    launch_train_with_config(train_conf, trainer=trainer)
  File "/usr/lib/python2.7/site-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    model.get_input_signature(), input,
  File "/usr/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 90, in get_input_signature
    inputs = self.inputs()
  File "/usr/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 122, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by neil3212080** [comment]
I use this method to run train1：python2 train1.py timit
How to modify the problem I encountered？？

**Comment by 13159590291** [comment]
i have the same problem. have you solved it now?
