### ISSUE TITLE
May I ask your hardware?

### ISSUE THREAD

**Issue by chikiuso** [andabi/deep-voice-conversion#2]
Hi, may I ask about your hardware specification? Such as which graphics card you use? How many ram your pc have? thanks.

**Comment by andabi** [comment]
@chikiuso I used a server which has 8 Nvidia Tesla P40 GPU and 200GB memory. But single GPU core was enough.

**Comment by HudsonHuang** [comment]
@andabi 

I ran your code on a server like this:
- 8 Nvidia GTX1080 
- about 40G graphics memory
- 200GB of memory

but the progress will always stop on " Creating TensorFlow device" and don't show any more infomation.

**Comment by andabi** [comment]
@HudsonHuang Please check the paths(data_path or something) in hparam.py again. If you set the paths incorrectly, the problem you mentioned could happen.

**Comment by andabi** [comment]
@tbfly I think the queue runner is not working properly. To debug, set queue=False in train1.py and then run and see what message is up.

**Comment by HudsonHuang** [comment]
@andabi 
I change the path to the currect one, but it raises：


Traceback (most recent call last):
  File "eval1.py", line 77, in <module>
    eval(logdir=logdir)
  File "eval1.py", line 45, in eval
    mfcc, ppg = get_batch(model.mode, model.batch_size)
  File "/home/lab-huang.zhongyi/workspace/deep-voice-conversion-master/data_load.py", line 256, in get_batch
    target_wavs = sample(wav_files, batch_size)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/random.py", line 324, in sample
    raise ValueError("Sample larger than population")
ValueError: Sample larger than population

**Comment by andabi** [comment]
@HudsonHuang It occurs when the number of wavfiles is smaller than the batch size.

**Comment by HudsonHuang** [comment]
@andabi and I check the len(wav_files) it's 0, seems it didn't get the files, I print the path in data_load.py of this line:[data_load.py](https://github.com/andabi/deep-voice-conversion/blob/24737a1bd1ad7f26639dccdac34562926d70ff03/data_load.py#L380)
and, it was 
`/home/lab-huang.zhongyi/workspace/deep-voice-conversion-master/datasets/timit/TIMIT/TRAIN/*/*/*.wav`
and my path is :
![image](https://user-images.githubusercontent.com/5734717/33159387-71b15cd8-d04d-11e7-98cd-bbb2be19cc9b.png)
Is it a currect path?

**Comment by tbfly** [comment]
@andabi 

2017-11-24 10:20:57.861347: I tensorflow/core/common_runtime/bfc_allocator.cc:683] Sum Total of in-use chunks: 685.56MiB
2017-11-24 10:20:57.861369: I tensorflow/core/common_runtime/bfc_allocator.cc:685] Stats: 
Limit:                   759037952
InUse:                   718866432
MaxInUse:                725436928
NumAllocs:                    1411
MaxAllocSize:            156712960

2017-11-24 10:20:57.861511: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ****************************************************************************************************
2017-11-24 10:20:57.861549: W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[32,401,2048]

It looks  "GeForce GTX 750 Ti " ResourceExhaustedError when use GPU mode.
😢

**Comment by tbfly** [comment]
@HudsonHuang   You should get "timit" datasheet somewhere. 😄

**Comment by tbfly** [comment]
Traceback (most recent call last):                                    
  File "train1.py", line 102, in <module>
    train(logdir=logdir)
  File "train1.py", line 76, in train
    summ, gs = sess.run([summ_op, global_step])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [32,?,40]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[32,?,40], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'Placeholder', defined at:
  File "train1.py", line 102, in <module>
    train(logdir=logdir)
  File "train1.py", line 18, in train
    model = Model(mode="train1", batch_size=hp.Train1.batch_size, queue=queue)
  File "/home/lite/deep-voice-conversion/models.py", line 22, in __init__
    self.x_mfcc, self.y_ppgs, self.y_spec, self.y_mel, self.num_batch = self.get_input(mode, batch_size, queue)
  File "/home/lite/deep-voice-conversion/models.py", line 43, in get_input
    x_mfcc = tf.placeholder(tf.float32, shape=(batch_size, None, hp_default.n_mfcc))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1599, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3091, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [32,?,40]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[32,?,40], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

If I set CUDA_VISIBLE_DEVICES="" force use CPU mode, the error is above.

**Comment by tbfly** [comment]
It seems CPU mode:
mfcc, ppg = get_batch(model.mode, model.batch_size)
sess.run(train_op, feed_dict={model.x_mfcc: mfcc, model.y_ppgs: ppg})

get_batch don't get the correct tensors?

**Comment by HudsonHuang** [comment]
@tbfly I think your problem is similar with mine, I did‘t get currect data to feed, may I ask you what is it your path to TIMIT dataset? Was it seems like this?
![image](https://user-images.githubusercontent.com/5734717/33194519-666067a2-d10b-11e7-8882-7d05a354ac78.png)

**Comment by SriramS32** [comment]
@HudsonHuang your problem may be that the '.wav' is case sensitive and your files have the .WAV extension instead. 
data_path = '{}/timit/TIMIT/TRAIN/*/*/*.WAV'.format(data_path_base)

**Comment by tbfly** [comment]
@SriramS32  I think it is a os dependence or version conflict issue. I run the same cold in OSX work perfect.  While I run it in Linux64, it cause the issue.

**Comment by tbfly** [comment]
@SriramS32 @andabi 
It seems cause by " tf.summary.merge_all".

**Comment by SriramS32** [comment]
@tbfly Yes, you are right. I can train on OSX with queue=True without any problems. Unfortunately, I don't have GPU support on non Linux machines. Interesting, is it expecting us to fill the placeholder even when we run the `summ_op`?

**Comment by tbfly** [comment]
`-            summ, gs = sess.run([summ_op, global_step])
+            if queue:
+                summ, gs = sess.run([summ_op, global_step])
+            else:
+                summ, gs = sess.run([summ_op, global_step], feed_dict={model.x_mfcc: mfcc, model.y_ppgs: ppg})`

@SriramS32 @andabi  It seems this modify fix the error.
In queue=False mode.
While queue=True mode, I need more time to figure out why not work.😄

**Comment by wyn314** [comment]
@tbfly  Have you found out why it doesn't work in queue=True mode?

**Comment by tiankong-hut** [comment]
I have resolved my problem , just install ffmpeg.
