### ISSUE TITLE
who can tell me what is case in train1...

### ISSUE THREAD

**Issue by Hjwjames** [andabi/deep-voice-conversion#28]
![123123](https://user-images.githubusercontent.com/31679768/37318557-2042fbcc-26a6-11e8-9749-618329833819.png)

I face this problem for long time....

**Comment by Hjwjames** [comment]
![1111](https://user-images.githubusercontent.com/31679768/37324303-b00e8a6a-26c3-11e8-896f-fc9f417d4643.png)

ok...I solve that problem now... but now I find the training stop at 0b [00:00 , ?b/2]

**Comment by JiaYK** [comment]
You don't have Timit datasets?

**Comment by VictoriaBentell** [comment]
You can get the trained weights [here](https://drive.google.com/open?id=1ExlBIpZO0mxBhK4WEoW2WhahG1dZwdKW) so you don't have to worry about Train1.

**Comment by Hjwjames** [comment]
mfcc, ppg = get_batch(model.mode, model.batch_size)
  File "G:\code\python\myfile\ASR\deep-voice-conversion-master\data_load.py", line 205, in get_batch
    mfcc, ppg = list(map(_get_zero_padded, list(zip(*[get_mfccs_and_phones(w, hp_default.sr) for w in target_wavs]))))
  File "G:\code\python\myfile\ASR\deep-voice-conversion-master\data_load.py", line 205, in <listcomp>
    mfcc, ppg = list(map(_get_zero_padded, list(zip(*[get_mfccs_and_phones(w, hp_default.sr) for w in target_wavs]))))
  File "G:\code\python\myfile\ASR\deep-voice-conversion-master\data_load.py", line 25, in get_mfccs_and_phones
    wav, sr = librosa.load(wav_file, sr=sr)
  File "G:\anaconda\lib\site-packages\librosa\core\audio.py", line 112, in load
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "G:/code/python/myfile/ASR/deep-voice-conversion-master/train1.py", line 117, in <module>
    train(logdir=logdir, hparams = hp)
  File "G:/code/python/myfile/ASR/deep-voice-conversion-master/train1.py", line 65, in train
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "G:\anaconda\lib\site-packages\audioread\__init__.py", line 114, in audio_open
    raise NoBackendError()
audioread.NoBackendError
>>>     execfile(filename, namespace)
  File "G:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile

**Comment by Hjwjames** [comment]
raise NoBackendError()
audioread.NoBackendError
It raise NobackendError...... @JiaYK @VictoriaBentell Do you know anything about it? Any comments would be much appreciated..... Thanks for your answer... I haven't put my Timit dataset in it last time

**Comment by VictoriaBentell** [comment]
According to [this thread](https://github.com/librosa/librosa/issues/219) you might want to try installing ffmpeg.

**Comment by JiaYK** [comment]
It's better to work under Linux. Tensorflow-gpu does not support Python2.7.

**Comment by Hjwjames** [comment]
@VictoriaBentell @JiaYK  Dear friends, your again help me solve this question. I install the ffmpeg,and it runs.
However, it comes a new problem, did you have meet? That is,

  target_wavs = sample(wav_files, batch_size)
  File "G:\anaconda\lib\random.py", line 317, in sample
    eval1.eval(logdir=logdir, hparams=hparams)
  File "G:\code\python\myfile\ASR\deep-voice-conversion-master\eval1.py", line 48, in eval
    mfcc, ppg = get_batch(model.mode, model.batch_size)
  File "G:\code\python\myfile\ASR\deep-voice-conversion-master\data_load.py", line 203, in get_batch
    execfile(filename, namespace)
  File "G:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "G:/code/python/myfile/ASR/deep-voice-conversion-master/train1.py", line 117, in <module>
    train(logdir=logdir, hparams = hp)
  File "G:/code/python/myfile/ASR/deep-voice-conversion-master/train1.py", line 77, in train
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile


    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative


Should I change the batch_size or anything else? My TIMIT dataset is 440MB, and the data is like this.
![11](https://user-images.githubusercontent.com/31679768/37584209-8a1c5b90-2b8f-11e8-8730-632e7fcf97db.png)

**Comment by Hjwjames** [comment]
@JiaYK @VictoriaBentell Dear friends, it this means I success training now? the epoch and step goes strange

INFO:tensorflow:Restoring parameters from ./logdir/default1/train1\epoch_24_step_24
Model loaded. mode: train1, model_name: epoch_24_step_24
acc: 0.0425952
loss: 3.95336


WARNING:tensorflow:From G:\code\python\myfile\ASR\deep-voice-conversion-master\models.py:73: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead
INFO:tensorflow:Restoring parameters from ./logdir/default1/train1\epoch_24_step_24
Model loaded. mode: train1, model_name: epoch_24_step_24
acc: 0.0476528
loss: 3.8893


WARNING:tensorflow:From G:\code\python\myfile\ASR\deep-voice-conversion-master\models.py:73: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead
INFO:tensorflow:Restoring parameters from ./logdir/default1/train1\epoch_26_step_26
Model loaded. mode: train1, model_name: epoch_26_step_26
acc: 0.0535262
loss: 3.91394


WARNING:tensorflow:From G:\code\python\myfile\ASR\deep-voice-conversion-master\models.py:73: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead
INFO:tensorflow:Restoring parameters from ./logdir/default1/train1\epoch_26_step_26
Model loaded. mode: train1, model_name: epoch_26_step_26
acc: 0.0459833
loss: 3.98388

**Comment by VictoriaBentell** [comment]
Those warnings are normal, so if you just let it keep training you should be fine.

**Comment by sachinsahoo11** [comment]
How did you solve the "argument" problem in the first case?
I am facing the same issue.

**Comment by Techmind** [comment]
@VictoriaBentell did y manage to get the whole pipeline working (with convert) ? 
Is 12 epochs of train1 enough ?

**Comment by CIDFarwin** [comment]
For those still struggling with the initial problem:

The "case" the script asks for is your name for the case, passed as an argument. e.g.
`python train1.py test`
where "test" can be anything. I suggest naming it after the dataset you use, such as
`python train1.py TIMIT`
if you're using the TIMIT dataset.

**Comment by ryancwalsh** [comment]
I'm surprised this isn't in the docs. It was confusing. Thanks to @CIDFarwin and https://github.com/andabi/deep-voice-conversion/issues/35#issuecomment-387593936

**Comment by oracle9i88** [comment]
test what erver 

Traceback (most recent call last):
  File "train1.py", line 76, in <module>
    print('case: {}, logdir: {}'.format(args.case1, args.case, logdir_train1))

**Comment by jackylee1** [comment]
> You can get the trained weights [here](https://drive.google.com/open?id=1ExlBIpZO0mxBhK4WEoW2WhahG1dZwdKW) so you don't have to worry about Train1.

thank you

**Comment by stephen-song** [comment]
reading hparams.py and u can find your answer
`    def set_hparam_yaml(self, case, default_file='hparams/default.yaml', user_file='hparams/hparams.yaml'):
        default_hp = load_hparam(default_file)                                  #default_hp是一个两级dic
        user_hp = load_hparam(user_file)                                        #user_hp是一个三级dic
        hp_dict = Dotdict(merge_dict(user_hp[case], default_hp) if case in user_hp else default_hp)
        for k, v in hp_dict.items():
            setattr(self, k, v)
        self._auto_setting(case)`
here the author merged two dicts: user_hp[case] & default_hp , when u dig into those .yaml files in hparams dir &merge_dict() function in hparams.py ,u can find that case may refer to different attempt on training hyperparamters(case just like a Fine-tuned version number) ,as u can see the merge_dict() fn replace params in default_hp with same named params in user_hp[case]

**Comment by stephen-song** [comment]
> raise NoBackendError()
> audioread.NoBackendError
> It raise NobackendError...... @JiaYK @VictoriaBentell Do you know anything about it? Any comments would be much appreciated..... Thanks for your answer... I haven't put my Timit dataset in it last time

i meet the same problem ,may i ask u for the answer?

**Comment by sunyuxiu** [comment]
> You can get the trained weights [here](https://drive.google.com/open?id=1ExlBIpZO0mxBhK4WEoW2WhahG1dZwdKW) so you don't have to worry about Train1.

hello,do you still have the trained weights from drive.google.com?I can't open the url and also can't download the weights.Could you send the weights to me or download then send to me?thanks.@VictoriaBentell

**Comment by VictoriaBentell** [comment]
> > You can get the trained weights [here](https://drive.google.com/open?id=1ExlBIpZO0mxBhK4WEoW2WhahG1dZwdKW) so you don't have to worry about Train1.
> 
> hello,do you still have the trained weights from drive.google.com?I can't open the url and also can't download the weights.Could you send the weights to me or download then send to me?thanks.@VictoriaBentell

It works for me in an incognito window on Windows 10 in Google Chrome. It's been a while but I think the file you should be looking at is "checkpoint"
