### ISSUE TITLE
run train1.py problem

### ISSUE THREAD

**Issue by ruby840124** [andabi/deep-voice-conversion#38]
I have a error,when I run train1.py

Traceback (most recent call last):
  File "train1.py", line 93, in <module>
    train(logdir=logdir)
  File "train1.py", line 17, in train
    model = Model(mode="train1", batch_size=hp.Train1.batch_size, queue=queue)
  File "/home/ruby/deep-voice-conversion/models.py", line 26, in __init__
    self.ppgs, self.pred_ppg, self.logits_ppg, self.pred_spec, self.pred_mel = self.net_template()
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 276, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=False)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 216, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/ruby/deep-voice-conversion/models.py", line 100, in _net2
    ppgs, preds_ppg, logits_ppg = self._net1()
  File "/home/ruby/deep-voice-conversion/models.py", line 75, in _net1
    out = cbhg(prenet_out, hp.Train1.num_banks, hp.Train1.hidden_units // 2, hp.Train1.num_highway_blocks, hp.Train1.norm_type, self.is_training)
  File "/home/ruby/deep-voice-conversion/modules.py", line 307, in cbhg
    is_training=is_training)  # (N, T, K * E / 2)
  File "/home/ruby/deep-voice-conversion/modules.py", line 189, in conv1d_banks
    output = normalize(output, type=norm_type, is_training=is_training, activation_fn=tf.nn.relu)
  File "/home/ruby/deep-voice-conversion/modules.py", line 116, in normalize
    beta = tf.get_variable("beta", shape=params_shape, initializer=tf.zeros_initializer)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 684, in _get_single_variable
    validate_shape=validate_shape)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 197, in __init__
    expected_shape=expected_shape)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 274, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/ruby/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 673, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: __init__() got multiple values for keyword argument 'dtype'

originally defined at:
  File "/home/ruby/deep-voice-conversion/models.py", line 25, in __init__
    self.net_template = tf.make_template('net', self._net2)

I put timit into datasets folder,
can someone solve this problem?
thank u.

**Comment by alapha23** [comment]
Hi!
i'm also working on net1 and trying to make it work. 
Regarding your question,
Did you partition the dataset?
