### ISSUE TITLE
Training on CPU, facing error in code conversion

### ISSUE THREAD

**Issue by navinthenapster** [andabi/deep-voice-conversion#54]
I like to edit the code for CPU computation, but facing with error as given below. I tried to change the Trainer and config but got stuck. need help

Traceback (most recent call last):
  File "train1.py", line 86, in <module>
    train(args, logdir=logdir_train1)
  File "train1.py", line 66, in train
    launch_train_with_config(train_conf, trainer )
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/interface.py", line 85, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/tower.py", line 202, in setup_graph
    input_callbacks = self._setup_input(inputs_desc, input)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/tower.py", line 218, in _setup_input
    return input.setup(inputs_desc)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/input_source/input_source_base.py", line 99, in setup
    return self.get_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/functools32/functools32.py", line 378, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/input_source/input_source_base.py", line 126, in get_callbacks
    before_train=lambda _: self.reset_state())] + self._get_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/input_source/input_source.py", line 245, in _get_callbacks
    return [cb, self._create_ema_callback(), _get_reset_callback(self._inf_ds)]
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/input_source/input_source.py", line 235, in _create_ema_callback
    size_ema_op = add_moving_summary(size, collection=None, decay=0.5)[0].op
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/summary.py", line 222, in add_moving_summary
    ctx = get_current_tower_context()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/tower.py", line 222, in get_current_tower_context
    assert _CurrentTowerContext is not None, "The function is supposed to be called under a TowerContext!"
AssertionError: The function is supposed to be called under a TowerContext!

**Comment by jiqizaisikao** [comment]
If we train  the model on GPU ,could it predict on cpu?

**Comment by carlfm01** [comment]
@jiqizaisikao Yes, but it will be slow, for me a 7s audio took 40s on a Tesla k80
