### ISSUE TITLE
wav = read_wav(wav_file, sr=hp.default.sr) KeyError: 'default'

### ISSUE THREAD

**Issue by BlcDec** [andabi/deep-voice-conversion#55]
Traceback (most recent call last):
  File "C:\Users\blcdec\ApplicationInstallPlace\Anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\blcdec\ApplicationInstallPlace\Anaconda3\envs\tensorflow\lib\site-packages\tensorpack\dataflow\parallel.py", line 162, in run
    for dp in self.ds.get_data():
  File "C:\Users\blcdec\ApplicationInstallPlace\Anaconda3\envs\tensorflow\lib\site-packages\tensorpack\dataflow\common.py", line 116, in get_data
    for data in self.ds.get_data():
  File "C:\Users\blcdec\project\deep-voice-conversion-master\deep-voice-conversion-master\data_load.py", line 35, in get_data
    yield get_mfccs_and_phones(wav_file=wav_file)
  File "C:\Users\blcdec\project\deep-voice-conversion-master\deep-voice-conversion-master\data_load.py", line 72, in get_mfccs_and_phones
    wav = read_wav(wav_file, sr=hp.default.sr)
KeyError: 'default'

win10
python36
because of what?

**Comment by navinthenapster** [comment]
some problem in your hparams/default.yaml . 
try  the below code in new python script

from hparam import hparam as hp
print hp
print hp.default

you must get a dict variable but in case you get empty dict
like output : {}

check the yaml files and set correctly

**Comment by BlcDec** [comment]
I can get the right value in train1.py by print, but not in data_load.py. 
The evaluation of hp in train1.py has no effect on hp in data_load.py.
After I called the function named set_hparam_yaml in data_load.py again, training was started.
My classmate ran successfully in Linux without any modification.
So I think it may be caused by system version.
Thank you for your reply!

**Comment by mindmapper15** [comment]
On hparam.py line 70, you will see this code.

hparam = Hparam()

In short, this code is cause of all the problem.
For every py file using hp.default.xxx, you will see "from hparam import hparam as hp" in the importing section.

Originally, this code imports hparam object as hp that has already been initialized at train1.py or train2.py with hp.set_hparam_yaml(args.caseX). All the variables you need are in the place so the codes are perfectly functional.

But on Windows platform, things are different.
For somehow in Windows, when Python read (or execute) "from hparam import hparam as hp" line in other py file, "hparam = Hparam()" code in hparam.py is executed **"again"** although hparam object has already been initialized. For this, all the variables are already stored in hparam object are completely wiped out. That's causing the error.

So, you either modify hparam.py and rest of py file which import hparam, or just run your code on Linux :)
