### ISSUE TITLE
problem on colab

### ISSUE THREAD

**Issue by jackylee1** [andabi/deep-voice-conversion#73]
Traceback (most recent call last):
  File "train1.py", line 10, in <module>
    from tensorpack.callbacks.saver import ModelSaver
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/callbacks/__init__.py", line 51, in <module>
    _global_import(module_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/callbacks/__init__.py", line 34, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/callbacks/base.py", line 5, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime

**Comment by sebasdeldi** [comment]
Hey @jackylee1 did you get to run this on Colab ?

**Comment by jackylee1** [comment]
no
