### ISSUE TITLE
IndexError: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by wuzhiyu666** [andabi/deep-voice-conversion#77]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\SANDSTORM\AppData\Roaming\Python\Python36\site-packages\tensorpack\dataflow\parallel.py", line 162, in run
    for dp in self.ds.get_data():
  File "C:\Users\SANDSTORM\AppData\Roaming\Python\Python36\site-packages\tensorpack\dataflow\common.py", line 116, in get_data
    for data in self.ds.get_data():
  File "C:\Users\SANDSTORM\Desktop\deep-voice-conversion-master\deep-voice-conversion-master\data_load.py", line 33, in get_data
    wav_file = random.choice(self.wav_files)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

Help!!!!!

**Comment by wishvivek** [comment]
@wuzhiyu666 Did you fix this error? If yes, how did you fix it?

**Comment by YashBangera7** [comment]
Check your hparams/default.yaml and the data_load.py for any data_paths and log_dir paths. Change it to the data paths of the train1 dataset and the train2 dataset on your machine. That should do it! :)

**Comment by qinyunchuan** [comment]
Where can I get the dataset for train1 and train2?
