### ISSUE TITLE
It doesn't work with CUDA 10

### ISSUE THREAD

**Issue by mianor64** [andabi/deep-voice-conversion#88]
Hi,

While trying to run train1.py, I receive this error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`

My server (with GPU) is setup to run CUDA 10. I also tried to run train1.py on Google Colab but it looks like CUDA 9.2 is used and I get the same error in both environments.

Is there a file to modify CUDA version used?

Thanks for your help.

**Comment by YashBangera7** [comment]
https://github.com/philferriere/dlwin 
This might help you :)

**Comment by mianor64** [comment]
CUDA 10, not Windows 10 :)

**Comment by mindmapper15** [comment]
You have to update tensorflow package to newest version. I think.
The author of this repository recommended to run this code on at least tensorflow 1.8, which is compiled with CUDA 9.

Either you have to build tensorflow 1.8 with CUDA 10, or just install newest version of tensorflow :)
