### ISSUE TITLE
ValueError: Specified colocation to an op that does not exist

### ISSUE THREAD

**Issue by thunderbird89** [andabi/deep-voice-conversion#95]
I tried using both this repo and @carlfm01's fork, but both of them are coming up with the same issues (MacOS X, Python 3.6.4).

First, with `tensorflow-gpu` installed, I get an error when trying to run `python train1.py testcase`, saying the Tensorflow native runtime failed to load. 
```
Failed to import tensorflow.
Traceback (most recent call last):
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train1.py", line 10, in <module>
    from tensorpack.callbacks.saver import ModelSaver
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/callbacks/__init__.py", line 51, in <module>
    _global_import(module_name)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/callbacks/__init__.py", line 34, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 7, in <module>
    import tensorflow as tf
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found


Failed to load the native TensorFlow runtime.
```
So I remove that, install `tensorflow` in its stead.

WIth `tensorflow 1.13.1` installed, I can at least _start_ to run the training, which exits after a few seconds with this gigantic stacktrace:
```
Traceback (most recent call last):
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2409, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'tower0/net1/cbhg/gru/bidirectional_rnn/fw/fw/while' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 415, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2413, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'tower0/net1/cbhg/gru/bidirectional_rnn/fw/fw/while' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 266, in _ProcessNewOps
    coloc_op = graph._get_operation_by_name_unsafe(coloc_op_name)  # pylint: disable=protected-access
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3629, in _get_operation_by_name_unsafe
    return self._nodes_by_name[name]
KeyError: 'tower0/net1/cbhg/gru/bidirectional_rnn/fw/fw/while'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train1.py", line 75, in <module>
    train(args, logdir=logdir_train1)
  File "train1.py", line 57, in train
    launch_train_with_config(train_conf, trainer=trainer)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/train/interface.py", line 84, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/train/tower.py", line 214, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 193, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 225, in call_for_each_tower
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 121, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 116, in call_for_each_tower
    ret.append(func())
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/train/tower.py", line 266, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorpack/train/tower.py", line 261, in compute_grad_from_inputs
    aggregation_method=self.AGGREGATION_METHOD)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 664, in gradients
    unconnected_gradients)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 965, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 420, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 965, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/ops/while_v2.py", line 245, in _WhileGrad
    cond_graph = _get_graph(op, "cond")
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/ops/while_v2.py", line 425, in _get_graph
    func_graph = function_def_to_graph.function_def_to_graph(fdef, input_shapes)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 55, in function_def_to_graph
    importer.import_graph_def(graph_def, name="")
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/Users/zmeggyesi/projects/deep-voice-conversion/env/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 274, in _ProcessNewOps
    (coloc_op_name, op.name))
ValueError: Specified colocation to an op that does not exist during import: tower0/net1/cbhg/gru/bidirectional_rnn/fw/fw/while in tower0_net1_cbhg_gru_bidirectional_rnn_fw_fw_while_loop_counter
```

Any ideas on what might I be doing wrong?

**Comment by juihsuanlee** [comment]
Hi, I have the same problem. Do you solve it ?
Thanks in advance.

**Comment by YashBangera7** [comment]
This might be possible due to the multiple versions of tensorflow. Try
reinstalling.
