### ISSUE TITLE
error when run train1

### ISSUE THREAD

**Issue by TTTJJJWWW** [andabi/deep-voice-conversion#96]
when i run 
$ python train1.py
error like that: what is the problem?

/home/iie/.conda/envs/deepvoice35/lib/python3.5/site-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "train1.py", line 17, in <module>
    from data_load import Net1DataFlow
  File "/home/iie/Downloads/deep-voice-conversion-master/data_load.py", line 14, in <module>
    from utils import normalize_0_1
  File "/home/iie/Downloads/deep-voice-conversion-master/utils.py", line 12, in <module>
    import tfplot
  File "/home/iie/.conda/envs/deepvoice35/lib/python3.5/site-packages/tfplot/__init__.py", line 14, in <module>
    from . import summary
  File "/home/iie/.conda/envs/deepvoice35/lib/python3.5/site-packages/tfplot/summary.py", line 14, in <module>
    summary_image_v1 = tf.compat.v1.summary.image
AttributeError: module 'tensorflow.tools.api.generator.api.compat' has no attribute 'v1'

**Comment by mindmapper15** [comment]
You have to install tensorflow-plot package.
Just type this line to terminal.

pip install git+https://github.com/wookayin/tensorflow-plot.git@master

**Comment by mindmapper15** [comment]
Sorry, It turns out that tensorflow-plot changed there Tensorflow APIs to r2.0
You have to downgrade tensorflow-plot package to 0.2.0
