### ISSUE TITLE
Can somebody provide me with 10000 epochs of train2.py's weights? 

### ISSUE THREAD

**Issue by YashBangera7** [andabi/deep-voice-conversion#98]

**Comment by hyuezhi** [comment]
are you still in training train2.py?

how do you train the NET1? I can not understand what the param 'case'  is ......

can you help me to start the training NET1?

sincerely
Regen

**Comment by YashBangera7** [comment]
> are you still in training train2.py?
> 
> how do you train the NET1? I can not understand what the param 'case' is ......
> 
> can you help me to start the training NET1?
> 
> sincerely
> Regen

Sure man .
The case parameter can be anything. The name you want your model to be saved as .
Example : 
if you give command as -> python train1.py -case "train1_net" -gpu 0 , it will be saved in the
 "case"-->"train1_net" folder. 
For starting train1 , go for the above command with the case name that you desire.

**Comment by hyuezhi** [comment]
Thank you for your kind help,  I figured out the "case" just means one kind of hparams: "default.yaml" or "hparams.yaml" 
but after running command "python train1.py -case "train1_net" -gpu 0"   or “python train1.py case”， I got the following log, and I have no idea what is going wrong... ...

Traceback (most recent call last):
  File "train1.py", line 17, in <module>
    from data_load import Net1DataFlow
  File "/home/huyuezhi/deep-voice-conversion/data_load.py", line 7, in <module>
    import librosa
  File "/home/huyuezhi/.local/lib/python2.7/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/huyuezhi/.local/lib/python2.7/site-packages/librosa/core/__init__.py", line 108, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/huyuezhi/.local/lib/python2.7/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/huyuezhi/.local/lib/python2.7/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/huyuezhi/.local/lib/python2.7/site-packages/librosa/util/utils.py", line 103, in <module>
    def valid_audio(y, mono=True):
  File "/home/huyuezhi/.local/lib/python2.7/site-packages/librosa/cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
  File "/home/huyuezhi/.local/lib/python2.7/site-packages/joblib/memory.py", line 918, in cachedir
    DeprecationWarning, stacklevel=2)
TypeError: expected string or buffer

I use python2.7

**Comment by hyuezhi** [comment]
I have successfully running the NET1 training, Thanks for you kind help!

**Comment by sebasdeldi** [comment]
How long did it take you guys to train NET1 ?
Do you think it is possible to run this project on google colab ? Maybe make a "notebook" port of this ?

**Comment by kabich** [comment]
@hyuezhi  hey can you tell us what is the command to run net1 please
